// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyGameDL;

namespace PartyGameDL.Migrations
{
    [DbContext(typeof(PartyGamesDBContext))]
    partial class PartyGamesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PartyGameModels.Blackjack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("WinLossRatio")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("GamesId");

                    b.ToTable("Blackjacks");
                });

            modelBuilder.Entity("PartyGameModels.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PartyGameModels.LightBike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WinLossRatio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GamesId");

                    b.ToTable("LightBikes");
                });

            modelBuilder.Entity("PartyGameModels.ScoreHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GamesId");

                    b.ToTable("ScoreHistories");
                });

            modelBuilder.Entity("PartyGameModels.Snake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AvgScore")
                        .HasColumnType("float");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<double>("HighScore")
                        .HasColumnType("float");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GamesId");

                    b.ToTable("Snakes");
                });

            modelBuilder.Entity("PartyGameModels.TicTacToe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WinLossRatio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GamesId");

                    b.ToTable("TicTacToes");
                });

            modelBuilder.Entity("PartyGameModels.Blackjack", b =>
                {
                    b.HasOne("PartyGameModels.Games", null)
                        .WithMany("Blackjacks")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGameModels.LightBike", b =>
                {
                    b.HasOne("PartyGameModels.Games", null)
                        .WithMany("LightBikes")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGameModels.ScoreHistory", b =>
                {
                    b.HasOne("PartyGameModels.Games", null)
                        .WithMany("GameScoreHistories")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGameModels.Snake", b =>
                {
                    b.HasOne("PartyGameModels.Games", null)
                        .WithMany("Snakes")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGameModels.TicTacToe", b =>
                {
                    b.HasOne("PartyGameModels.Games", null)
                        .WithMany("TicTacToes")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGameModels.Games", b =>
                {
                    b.Navigation("Blackjacks");

                    b.Navigation("GameScoreHistories");

                    b.Navigation("LightBikes");

                    b.Navigation("Snakes");

                    b.Navigation("TicTacToes");
                });
#pragma warning restore 612, 618
        }
    }
}
